permissions:
  contents: write

name: Run Scraper Frequently

on:
  schedule:
    - cron: "*/1 * * * *"   # every 5 minutes (UTC time)
  workflow_dispatch:        # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: crowd_meter_scraper.py

      - name: Commit CSV back to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add crowd_meter_data.csv
          git commit -m "Update crowd meter data [skip ci]" || echo "No changes to commit"
          git push
